
function drawOscillator(algoTrader, axesHandle, setSelector, initIndex, endIndex)

% Parameters
riseThreshold = algoTrader.RiseThreshold;
fallThreshold = algoTrader.FallThreshold;
dateTime = algoTrader.DataSerie.DateTime(initIndex:endIndex);

% Relative Strength Index and Moving Average
[relativeStrengthIndex, movingAverage] = bareOutput(algoTrader, initIndex, endIndex);

% DataSerie
symbolCode = algoTrader.DataSerie.SymbolCode;
compressionType = algoTrader.DataSerie.CompressionType;
compressionUnits = algoTrader.DataSerie.CompressionUnits;

hold on;
plot(axesHandle, ...
    dateTime, ...
    relativeStrengthIndex, ...
    'b', ...
    'LineWidth',1 ...
    );
plot(axesHandle, ...
    dateTime, ...
    movingAverage, ...
    'Color', [0 255 127]/255, ...
    'LineWidth', 1 ...
    );
plot(axesHandle, ...
    [dateTime(1), dateTime(end)], ...
    [riseThreshold, riseThreshold], ...
    'm', ...
    'LineWidth', 1 ...
    );
plot(axesHandle, ...
    [dateTime(1), dateTime(end)], ...
    [fallThreshold, fallThreshold], ...
    'c', ...
    'LineWidth', 1 ...
    );
hold off;

% Itemize
% Information and fixes
if Settings.ShowLegend
    legend(axesHandle, 'String', { 'Relative Strength Index' 'Moving Average' 'RiseThreshold', 'FallThreshold' }, 'Location', 'NorthWest');
end
xlabel(axesHandle, '\bfDate');
ylabel(axesHandle, '\bfValue');
xlim(axesHandle, [dateTime(1) dateTime(end)]);

% Axes Title
title(axesHandle, '\bfRelative Strength Index Crossing');

% Description
description = [ ...
    'Relative Strength Index Crossing | ', ...
    symbolCode, ' - ', ...
    compressionType, ' ', '(', num2str(compressionUnits) ,')', ...
    ' from ', datestr(dateTime(1)), ...
    ' to ', datestr(dateTime(end)) ...
    ];

% Figure Name
figureHandle = get(axesHandle,'Parent');
if isempty(get(figureHandle,'Name'))
    set(figureHandle,'Name',description);
end

end
