
function tsobj = struct2mfts(stockData)

tsobj = fints( ...
    datenum(stockData.date), ...    % Date
    [ ...                           % Data values
        stockData.open, ...         % Open
        stockData.high, ...         % High
        stockData.low, ...          % Low
        stockData.close, ...        % Close
        stockData.volume ...        % Volume
    ], ...
    { ...                           % Data names
        'open', ...
        'high', ...
        'low', ...
        'close', ...
        'volume' ...
    }, ...
    stockData.frecuency, ...        % Frecuency
    stockData.symbol ...            % Symbol as description
    );

end
