
function wideSet(algoTrader, name, values)

if length(values) > 1
    
    for i = 1:length(algoTrader.Fragment)
    
        subsasgn( ...
            algoTrader.Fragment(i), ...
            struct( ...
                'type','.', ...
                'subs', name ...
                ), ...
            values{i} ...
            );
    
    end
    
else
    
    for i = 1:length(algoTrader.Fragment)
    
        subsasgn( ...
            algoTrader.Fragment(i), ...
            struct( ...
                'type','.', ...
                'subs', name ...
                ), ...
            values ...
            );
    
    end
    
end

end
