
function plotOscillatorCustomizer(te, startIndex, endIndex, axesHandle, varargin)

% FinancialTimeSerie
fts = te.FinancialTimeSerie;

stochastic = stoch(fts.High, fts.Low, fts.Close, te.StochasticSamples);


hold on;
plot(axesHandle, ...
    fts.Date(startIndex:endIndex), ...
    stochastic, ...
    'b', ...
    'LineWidth', 1 ...
    );
plot(axesHandle, ...
    [fts.Date(startIndex), fts.Date(endIndex)], ...
    [te.HighThreshold, te.HighThreshold], ...
    'r', ...
    'LineWidth', 2 ...
    );
plot(axesHandle, ...
    [fts.Date(startIndex), fts.Date(endIndex)], ...
    [te.LowThreshold, te.LowThreshold], ...
    'r', ...
    'LineWidth', 2 ...
    );
hold off;

title(axesHandle, '\bfStochastic');
%legend(axesHandle, 'Stochastic');
xlabel(axesHandle, '\bfDate');
ylabel(axesHandle, '\bfValue');
xlim(axesHandle, [fts.Date(startIndex) fts.Date(endIndex)]);

end
