
function drawSerie(dataSerie, axesHandle, initIndex, endIndex)

open = dataSerie.Open(initIndex:endIndex);
high = dataSerie.High(initIndex:endIndex);
low = dataSerie.Low(initIndex:endIndex);
close = dataSerie.Close(initIndex:endIndex);
dateTime = dataSerie.DateTime(initIndex:endIndex);
symbolCode = dataSerie.SymbolCode;
compressionType = dataSerie.CompressionType;
compressionUnits = dataSerie.CompressionUnits;

% Draw
hold on;
plot(axesHandle, ...
    dateTime, open, ...
    Settings.OpenLineStyle, ...
    'Color', Settings.OpenLineColor, ...
    'LineWidth', Settings.PriceLineWidth ...
    );
plot(axesHandle, ...
    dateTime, high, ...
    Settings.HighLineStyle, ...
    'Color', Settings.HighLineColor, ...
    'LineWidth', Settings.PriceLineWidth ...
    );
plot(axesHandle, ...
    dateTime, low, ...
    Settings.LowLineStyle, ...
    'Color', Settings.LowLineColor, ...
    'LineWidth', Settings.PriceLineWidth ...
    );
plot(axesHandle, ...
    dateTime, close, ...
    Settings.CloseLineStyle, ...
    'Color', Settings.CloseLineColor, ...
    'LineWidth', Settings.PriceLineWidth ...
    );
hold off;

% Itemize
% Information and fixes
legend(axesHandle, 'Open','High','Low','Close','Location','NorthWest');
xlabel(axesHandle, '\bfDateTime');
ylabel(axesHandle, '\bfPrice');
xlim(axesHandle, [dateTime(1) dateTime(end)]);

% Axes Title
title(axesHandle, '\bfSerie');

% Description
description = [ ...
    'Serie | ', ...
    symbolCode, ' - ', ...
    compressionType, ' ', '(', num2str(compressionUnits) ,')', ...
    ' from ', datestr(dateTime(1)), ...
    ' to ', datestr(dateTime(end)) ...
    ];

% Figure Name
figureHandle = get(axesHandle,'Parent');
if isempty(get(figureHandle,'Name'))
    set(figureHandle,'Name',description);
end

end
