
function fts = get(symbol, varargin)

stockData = getStockDataYahoo(symbol, varargin{:});
%stockData = getStockDataGoogle(symbol, varargin{:});

fts = FinancialTimeSerie( ...
    stockData.symbol, ...
    stockData.frecuency, ...
    stockData.date, ...
    stockData.open, ...
    stockData.high, ...
    stockData.low, ...
    stockData.close, ...
    stockData.volume ...
    );

end
