
function plotVolumeCustomizer(fts, startIndex, endIndex, axesHandle, varargin)

bar(axesHandle, ...
    fts.Date(startIndex:endIndex), ...
    fts.Volume(startIndex:endIndex), ...
    'FaceColor', Default.VolumeFaceColor, ...
    'EdgeColor', Default.VolumeEdgeColor, ...
    'BarWidth', Default.VolumeBarWidth ...
    );
% Information and fixes
title('\bfTransaction volume');
%legend(axesHandle, 'Volume');
xlabel(axesHandle, '\bfDate');
ylabel(axesHandle, '\bfQuantity');
xlim(axesHandle, [fts.Date(startIndex) fts.Date(endIndex)]);

end
