
function plotSerieCustomizer(fts, startIndex, endIndex, axesHandle, fun, varargin)

description = varargin{1};

hold on;
plot(axesHandle, ...
    fts.Date(startIndex:endIndex), fun(fts.Open(startIndex:endIndex)), ...
    Default.OpenLineSpec, ...
    'LineWidth', Default.PriceLineWidth ...
    );
plot(axesHandle, ...
    fts.Date(startIndex:endIndex), fun(fts.High(startIndex:endIndex)), ...
    Default.HighLineSpec, ...
    'LineWidth', Default.PriceLineWidth ...
    );
plot(axesHandle, ...
    fts.Date(startIndex:endIndex), fun(fts.Low(startIndex:endIndex)), ...
    Default.LowLineSpec, ...
    'LineWidth', Default.PriceLineWidth ...
    );
plot(axesHandle, ...
    fts.Date(startIndex:endIndex), fun(fts.Close(startIndex:endIndex)), ...
    Default.CloseLineSpec, ...
    'LineWidth', Default.PriceLineWidth ...
    );
hold off;
% Information and fixes
title(['\bf', strrep(description, '^', '\^')]);
legend(axesHandle, 'Open','High','Low','Close','Location','NorthWest');
xlabel(axesHandle, '\bfDate');
ylabel(axesHandle, ['\bfPrice', ' [ fun = ', func2str(fun), ' ]']);
xlim(axesHandle, [fts.Date(startIndex) fts.Date(endIndex)]);

end
