
function ftsSubset = subset(fts, startRange, endRange)

% startRange
if ~exist('startRange','var'); startRange = 1; end
% endRange
if ~exist('endRange','var'); endRange = fts.Length; end

[startIndex, endIndex] = fts.range2index(startRange, endRange);

% We must copy every property because FinancialTimeSerie extends handle
ftsSubset = FinancialTimeSerie( ...
    fts.Symbol, ...
    fts.Frecuency, ...
    fts.Date(startIndex:endIndex), ...
    fts.Open(startIndex:endIndex), ...
    fts.High(startIndex:endIndex), ...
    fts.Low(startIndex:endIndex), ...
    fts.Close(startIndex:endIndex), ...
    fts.Volume(startIndex:endIndex) ...
    );

end
