
function drawOscillator(algoTrader, axesHandle, initIndex, endIndex)

% Parameters
samples = algoTrader.Samples;
highThreshold = algoTrader.HighThreshold;
lowThreshold = algoTrader.LowThreshold;
serie = algoTrader.DataSerie.Serie(max(initIndex-samples+1,1):endIndex);
dateTime = algoTrader.DataSerie.DateTime(initIndex:endIndex);

symbolCode = algoTrader.DataSerie.SymbolCode;
compressionType = algoTrader.DataSerie.CompressionType;
compressionUnits = algoTrader.DataSerie.CompressionUnits;

relativeStrengthIndex = rsindex(serie, samples);
relativeStrengthIndex = relativeStrengthIndex(end-(endIndex-initIndex):end);

hold on;
plot(axesHandle, ...
    dateTime, ...
    relativeStrengthIndex, ...
    'k', ...
    'LineWidth',1 ...
    );
plot(axesHandle, ...
    [dateTime(1), dateTime(end)], ...
    [highThreshold, highThreshold], ...
    'm', ...
    'LineWidth', 1 ...
    );
plot(axesHandle, ...
    [dateTime(1), dateTime(end)], ...
    [lowThreshold, lowThreshold], ...
    'c', ...
    'LineWidth', 1 ...
    );
hold off;

% Itemize
% Information and fixes
legend(axesHandle, 'String', { 'Relative Strength Index' 'High Threshold' 'Low Threshold' }, 'Location', 'NorthWest');
xlabel(axesHandle, '\bfDate');
ylabel(axesHandle, '\bfValue');
xlim(axesHandle, [dateTime(1) dateTime(end)]);

% Axes Title
title(axesHandle, '\bfRelative Strength Index');

% Description
description = [ ...
    'Relative Strength Index | ', ...
    symbolCode, ' - ', ...
    compressionType, ' ', '(', num2str(compressionUnits) ,')', ...
    ' from ', datestr(dateTime(1)), ...
    ' to ', datestr(dateTime(end)) ...
    ];

% Figure Name
figureHandle = get(axesHandle,'Parent');
if isempty(get(figureHandle,'Name'))
    set(figureHandle,'Name',description);
end

end
