
function recursiveUpdate(algoTrader, propertyName, src, event)

for i = 1:length(algoTrader.InnerAlgoTrader)
    
    subsasgn( ...
        algoTrader.InnerAlgoTrader{i}, ...
        struct( ...
            'type', '.', ...
            'subs', propertyName ...
            ), ...
        subsref( ...
            algoTrader, ...
            struct( ...
                'type', '.', ...
                'subs', propertyName ...
                ) ...
            ) ...
        );
    
end

end
