
function drawOscillator(algoTrader, axesHandle, setSelector, initIndex, endIndex)

% Parameters
dateTime = algoTrader.DataSerie.DateTime(initIndex:endIndex);

%
[ ...
    plusDirectionalMovement, ...
    minusDirectionalMovement, ...
    directionalMovementIndex, ...
    averageDirectionalIndex ...
] = algoTrader.bareOutput(initIndex, endIndex);

% DataSerie
symbolCode = algoTrader.DataSerie.SymbolCode;
compressionType = algoTrader.DataSerie.CompressionType;
compressionUnits = algoTrader.DataSerie.CompressionUnits;

hold on;
plot(axesHandle, ...
    dateTime, ...
    plusDirectionalMovement, ...
    'c', ...
    'LineWidth',1 ...
    );
plot(axesHandle, ...
    dateTime, ...
    minusDirectionalMovement, ...
    'm', ...
    'LineWidth',1 ...
    );
plot(axesHandle, ...
    dateTime, ...
    averageDirectionalIndex, ...
    'b', ...
    'LineWidth',1 ...
    );
hold off;

% Itemize
% Information and fixes
if Settings.ShowLegend
    legend(axesHandle, 'String', { '+Directional Movement' '-Directional Movement' 'ADX' } , 'Location', 'NorthWest');
end
xlabel(axesHandle, '\bfDate');
ylabel(axesHandle, '\bfValue');
xlim(axesHandle, [dateTime(1) dateTime(end)]);

% Axes Title
title(axesHandle, '\bfAverageDirectionalIndex');

% Description
description = [ ...
    'AverageDirectionalIndex | ', ...
    symbolCode, ' - ', ...
    compressionType, ' ', '(', num2str(compressionUnits) ,')', ...
    ' from ', datestr(dateTime(1)), ...
    ' to ', datestr(dateTime(end)) ...
    ];

% Figure Name
figureHandle = get(axesHandle,'Parent');
if isempty(get(figureHandle,'Name'))
    set(figureHandle,'Name',description);
end

end
