% Initializer script

%clc;
fprintf('Initializing TradingPlatform\n');

%% Symbols

startDate = '2008-01-01';
symbolArray = { ...
    ...                                             % Indexes
    ...
    ...{ '^DJI', ...                                   % Dow Jones Industrial Average
    ...    {'startDate', startDate} } ...
    ...{ '^IXIC', ...                                  % NASDAQ Composite
    ...    {'startDate', startDate} } ...
    ...{ '^FTSE', ...                                  % FTSE 100
    ...    {'startDate', '2002-12-03'} } ...
    ...{ '^GSPC', ...                                  % S&P 500 INDEX
    ...    {'startDate', startDate} } ...
    ...{ '^GSPTSE', ...                                % S&P/TSX Composite index
    ...    {'startDate', '2000-03-27'} } ...
    ...{ '^ATX', ...                                   % Austrian Trade Index
    ...    {'startDate', '2004-10-12'} } ...
    ...{ '^BFX', ...                                   % EURONEXT BEL-20
    ...    {'startDate', '2004-10-11'} } ...
    ...{ '^AEX', ...                                   % Amsterdam
    ...    {'startDate', '2004-10-11'} } ...
    ...
    ...
    ...                                             % Big companies
    ...
    { 'IBM', ...                                    % International Business Machines Corp.
        {'startDate', startDate} } ...
    { 'INTC', ...                                   % Intel Corporation
        {'startDate', startDate} } ...
    { 'AMD', ...                                    % Advanced Micro Devices, Inc.
        {'startDate', startDate} } ...
    { 'NVDA', ...                                   % NVIDIA Corp.
        {'startDate', startDate} } ...
    { 'GOOG', ...                                   % Google Inc.
        {'startDate', startDate} } ...
    { 'YHOO', ...                                   % Yahoo Inc.
        {'startDate', startDate} } ...
    { 'MSFT', ...                                   % Microsoft Corporation
        {'startDate', startDate} } ...
    { 'AAPL', ...                                   % Apple Inc.
        {'startDate', startDate} } ...
    { 'ATVI', ...                                   % Activision Blizzard, Inc.
        {'startDate', startDate} } ...
    { 'F', ...                                      % Ford Motor Co.
        {'startDate', startDate} } ...
    { 'GE', ...                                     % General Electric Co.
        {'startDate', startDate} } ...
    { 'XOM', ...                                    % Exxon Mobil Corp.
        {'startDate', startDate} } ...
    { 'BP', ...                                     % BP p.l.c.
        {'startDate', startDate} } ... 
    { 'TEF', ...                                    % Telefonica, S.A.
        {'startDate', startDate} }...
    { 'STD', ...                                    % Banco Santander, S.A.
        {'startDate', startDate} }...
    { 'BBVA', ...                                   % Banco Bilbao Vizcaya Argentaria, S.A.
        {'startDate', startDate} }...
    { 'REP', ...                                    % Repsol YPF S.A.
        {'startDate', startDate} }...
    { 'ING', ...                                    % ING Groep N.V.
        {'startDate', startDate} }...
    { 'AEG', ...                                    % AEGON N.V.
        {'startDate', startDate} }...
    };


%%symbolArray = { { 'GOOG', {'startDate', startDate} } };

%% Trading engines

tradingEngineArray = { ...
    ...
    % Based on indicators
    ...
    { 'ma',     @MovingAverage } ...
    { 'mat',    @MovingAverageThreshold } ...
    { 'mad',    @MovingAverageDisplaced } ...
    ...
    { 'mac',    @MovingAveragesCrossing } ...
    { 'mact',   @MovingAveragesCrossingThreshold } ...
    ...
    { 'maf',    @MovingAverageFragmented.initialize } ...
    { 'matf',   @MovingAverageThresholdFragmented.initialize } ...
    ...
    { 'macf',   @MovingAveragesCrossingFragmented.initialize } ...
    { 'mactf',  @MovingAveragesCrossingThresholdFragmented.initialize } ...
    ...
    { 'bb',     @BollingerBands.initialize } ...
    { 'bbi',    @BollingerBandsInverse.initialize } ...
    ...
    { 'sc',     @Stochastic.initialize } ...
    { 'sccrs',  @StochasticCrossing.initialize } ...
    ...
    { 'rsi',    @RelativeStrengthIndex.initialize } ...
    ...
    { 'macd',   @MovingAverageConvergenceDivergence.initialize }
    ...
    };


%% Initialize

%initEngine;
initSymbol;


%% Shortcuts

% FTS = @(symbol) FinancialTimeSerie.get(symbol)
% MA = @MovingAverage



