
function performance = fitness(algoTrader, fitnessMethodWithArguments)

if ~exist('fitnessMethodWithArguments','var')
    
    performance = algoTrader.profitLoss(Settings.TrainingSet);
    
else 
    
    if isa(fitnessMethodWithArguments,'function_handle')
        method = fitnessMethodWithArguments;
        methodArguments = {};
    else
        method = fitnessMethodWithArguments{1};
        methodArguments = fitnessMethodWithArguments(2:end);
    end
    
    [ ...
        positionType, ...
        openIndex, ...
        closeIndex, ...
        openDate, ...
        closeDate, ...
        openPrice, ...
        closePrice, ...
        profitLoss ...
    ] ...
    = algoTrader.positionsLog(Settings.TrainingSet);
    
    performance = method( ...
        [ ...
            positionType, ...
            openIndex, ...
            closeIndex, ...
            openDate, ...
            closeDate, ...
            openPrice, ...
            closePrice, ...
            profitLoss ...
        ], ...
        methodArguments{:} ...
        );
    
end

end
